# Generated by Django 5.2 on 2025-04-19 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='dispute_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='dispute_resolved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='dispute_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending Review'), ('Under_Review', 'Under Review'), ('Seller_Responded', 'Seller Responded'), ('Mediation', 'In Mediation'), ('Resolved_Seller', 'Resolved in Favor of Seller'), ('Resolved_Buyer', 'Resolved in Favor of Buyer'), ('Resolved_Compromise', 'Resolved with Compromise')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='resolution_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Funded', 'Funded'), ('Released', 'Released'), ('Refunded', 'Refunded'), ('Disputed', 'Disputed')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin_message', models.BooleanField(default=False)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='dispute_messages/')),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_messages', to='core.escrowtransaction')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='dispute_attachments/')),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_responses', to='core.escrowtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisputeTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_change', models.CharField(blank=True, choices=[('Pending', 'Pending Review'), ('Under_Review', 'Under Review'), ('Seller_Responded', 'Seller Responded'), ('Mediation', 'In Mediation'), ('Resolved_Seller', 'Resolved in Favor of Seller'), ('Resolved_Buyer', 'Resolved in Favor of Buyer'), ('Resolved_Compromise', 'Resolved with Compromise')], max_length=20, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_timeline', to='core.escrowtransaction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
