# Generated by Django 5.2 on 2025-04-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_escrowtransaction_dispute_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='confirmation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='scheduled_release_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
