# Generated by Django 5.2 on 2025-04-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_rating_fields'),
        ('core', '0003_sellerverification'),
    ]

    operations = [
    ]
