# Generated by Django 5.1.6 on 2025-04-05 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('established_year', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('primary_crop', models.CharField(blank=True, max_length=100)),
                ('soil_type', models.CharField(blank=True, choices=[('Loamy', 'Loamy'), ('Clay', 'Clay'), ('Sandy', 'Sandy')], max_length=20)),
                ('description', models.TextField()),
                ('is_organic_certified', models.BooleanField(default=False)),
                ('is_fair_trade_certified', models.BooleanField(default=False)),
                ('gallery_images', models.ImageField(blank=True, null=True, upload_to='farm_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
