# Generated by Django 5.2 on 2025-04-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_create_review_model'),
        ('core', '0004_merge_0002_add_rating_fields_0003_sellerverification'),
    ]

    operations = [
    ]
